# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 5K Bakas Charity Trail Run and 1 Mile Fun Walk/Trot

tagline: Bakas 5K Trail Run & 1 Mile Fun Walk~Trot

email: info@5kbakas.com

description: Register today to join the Bakas 1st annual 5K Run / 1 mile Walk~Trot

baseurl: "/5kbakas" # the subpath of your site, e.g. /blog
url: "http://www.5kbakas.com/" # the base hostname & protocol for your site

event_date: 2016-11-05 00:00:00 EST

facebook_link: https://www.facebook.com/BakasRidingCenter

# Build settings
markdown: kramdown

gems:
 - jekyll-coffeescript
 - jekyll-paginate
